version: "3.8"

services:
  app:
    container_name: app
    build: .
    # command: uvicorn app.main:app --host 0.0.0.0 --port 80
    ports:
      - "8000:80"
    depends_on:
      - postgresql_database
    restart: always
    environment:
      - DATABASE_URL=postgresql://myuser:123456@postgresql_database:5432/postgres_database
  postgresql_database:
    container_name: postgresql_database
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres_database
    restart: always
volumes:
  postgres_data:
